package com.yaadanial.lachasseauxblocks.plugin;

import java.util.ArrayList;
import java.util.List;

import org.bukkit.Material;

public class AskingBlock {

	private List<BlockTypeData> askingBlock;

	public AskingBlock() {
		this.askingBlock = new ArrayList<BlockTypeData>();
		init();
	}

	private void init() {
		//@formatter:off
		askingBlock.add(new BlockTypeData(Material.STONE, 0));						// (ID=1)Stone
		askingBlock.add(new BlockTypeData(Material.STONE, 1));						// (ID=1)Granite
		askingBlock.add(new BlockTypeData(Material.STONE, 2));						// (ID=1)Granite Polie
		askingBlock.add(new BlockTypeData(Material.STONE, 3));						// (ID=1)Diorite
		askingBlock.add(new BlockTypeData(Material.STONE, 4));						// (ID=1)Diorite Polie
		askingBlock.add(new BlockTypeData(Material.STONE, 5));						// (ID=1)Andésite
		askingBlock.add(new BlockTypeData(Material.STONE, 6));						// (ID=1)Andésite Polie
		askingBlock.add(new BlockTypeData(Material.GRASS, 0));						// (ID=2)Herbe
		askingBlock.add(new BlockTypeData(Material.DIRT, 0));						// (ID=3)Dirt
		askingBlock.add(new BlockTypeData(Material.DIRT, 1));						// (ID=3)Coarse Dirt
		askingBlock.add(new BlockTypeData(Material.DIRT, 2));						// (ID=3)Podzol
		askingBlock.add(new BlockTypeData(Material.COBBLESTONE, 0));				// (ID=4)CobbleStone
		askingBlock.add(new BlockTypeData(Material.WOOD, 0));						// (ID=5)Oak Planks
		askingBlock.add(new BlockTypeData(Material.WOOD, 1));						// (ID=5)Spruce Planks
		askingBlock.add(new BlockTypeData(Material.WOOD, 2));						// (ID=5)Birch Planks
		askingBlock.add(new BlockTypeData(Material.WOOD, 3));						// (ID=5)Jungle Planks
		askingBlock.add(new BlockTypeData(Material.WOOD, 4));						// (ID=5)Acacia Planks
		askingBlock.add(new BlockTypeData(Material.WOOD, 5));						// (ID=5)Dark Planks
		askingBlock.add(new BlockTypeData(Material.SAND, 0));						// (ID=12)Sand
		askingBlock.add(new BlockTypeData(Material.SAND, 1));						// (ID=12)Red Sand
		askingBlock.add(new BlockTypeData(Material.GRAVEL, 0));						// (ID=13)Gravel
		askingBlock.add(new BlockTypeData(Material.GOLD_ORE, 0));					// (ID=14)Gold Ore
		askingBlock.add(new BlockTypeData(Material.IRON_ORE, 0));					// (ID=15)Iron Ore
		askingBlock.add(new BlockTypeData(Material.COAL_ORE, 0));					// (ID=16)Coal Ore
		askingBlock.add(new BlockTypeData(Material.LOG, 0));						// (ID=17)Oak Wood
		askingBlock.add(new BlockTypeData(Material.LOG, 1));						// (ID=17)Spruce Wood
		askingBlock.add(new BlockTypeData(Material.LOG, 2));						// (ID=17)Birch Wood
		askingBlock.add(new BlockTypeData(Material.LOG, 3));						// (ID=17)Jungle Wood
		askingBlock.add(new BlockTypeData(Material.LEAVES, 0));						// (ID=18)Oak Leaves
		askingBlock.add(new BlockTypeData(Material.LEAVES, 1));						// (ID=18)Spruce Leaves
		askingBlock.add(new BlockTypeData(Material.LEAVES, 2));						// (ID=18)Birch Leaves
		askingBlock.add(new BlockTypeData(Material.LEAVES, 3));						// (ID=18)Jungle Leaves
		askingBlock.add(new BlockTypeData(Material.SPONGE, 0));						// (ID=19)Sponge
		askingBlock.add(new BlockTypeData(Material.SPONGE, 1));						// (ID=19)Wet Sponge
		askingBlock.add(new BlockTypeData(Material.GLASS, 0));						// (ID=20)Glass
		askingBlock.add(new BlockTypeData(Material.LAPIS_ORE, 0));					// (ID=21)Lapis Ore
		askingBlock.add(new BlockTypeData(Material.LAPIS_BLOCK, 0));				// (ID=22)Lapis Block
		askingBlock.add(new BlockTypeData(Material.DISPENSER, 0));					// (ID=23)Dispenser
		askingBlock.add(new BlockTypeData(Material.SANDSTONE, 0));					// (ID=24)SandStone
		askingBlock.add(new BlockTypeData(Material.SANDSTONE, 1));					// (ID=24)Chiseled SandStone
		askingBlock.add(new BlockTypeData(Material.SANDSTONE, 2));					// (ID=24)Sprooth SandStone
		askingBlock.add(new BlockTypeData(Material.NOTE_BLOCK, 0));					// (ID=25)Note Block
		askingBlock.add(new BlockTypeData(Material.POWERED_RAIL, 0));				// (ID=27)Powered Rail
		askingBlock.add(new BlockTypeData(Material.DETECTOR_RAIL, 0));				// (ID=28)Detector_Rail
		askingBlock.add(new BlockTypeData(Material.PISTON_STICKY_BASE, 0));			// (ID=29)Sticky Piston
		askingBlock.add(new BlockTypeData(Material.WEB, 0));						// (ID=30)Cobweb
		askingBlock.add(new BlockTypeData(Material.PISTON_BASE, 0));				// (ID=33)Piston
		askingBlock.add(new BlockTypeData(Material.WOOL, 0));						// (ID=35)Wool
		askingBlock.add(new BlockTypeData(Material.WOOL, 1));						// (ID=35)Orange Wool
		askingBlock.add(new BlockTypeData(Material.WOOL, 2));						// (ID=35)Magenta Wool
		askingBlock.add(new BlockTypeData(Material.WOOL, 3));						// (ID=35)Light Blue Wool
		askingBlock.add(new BlockTypeData(Material.WOOL, 4));						// (ID=35)Yellow Wool
		askingBlock.add(new BlockTypeData(Material.WOOL, 5));						// (ID=35)Lime Wool
		askingBlock.add(new BlockTypeData(Material.WOOL, 6));						// (ID=35)Pink Wool
		askingBlock.add(new BlockTypeData(Material.WOOL, 7));						// (ID=35)Gray Wool
		askingBlock.add(new BlockTypeData(Material.WOOL, 8));						// (ID=35)Light Gray Wool
		askingBlock.add(new BlockTypeData(Material.WOOL, 9));						// (ID=35)Cyan Wool
		askingBlock.add(new BlockTypeData(Material.WOOL, 10));						// (ID=35)Purple Wool
		askingBlock.add(new BlockTypeData(Material.WOOL, 11));						// (ID=35)Blue Wool
		askingBlock.add(new BlockTypeData(Material.WOOL, 12));						// (ID=35)Brown Wool
		askingBlock.add(new BlockTypeData(Material.WOOL, 13));						// (ID=35)Green Wool
		askingBlock.add(new BlockTypeData(Material.WOOL, 14));						// (ID=35)Red Wool
		askingBlock.add(new BlockTypeData(Material.WOOL, 15));						// (ID=35)Black Wool
		askingBlock.add(new BlockTypeData(Material.GOLD_BLOCK, 0));					// (ID=41)Gold Block
		askingBlock.add(new BlockTypeData(Material.IRON_BLOCK, 0));					// (ID=42)Iron Block
		askingBlock.add(new BlockTypeData(Material.STEP, 0));						// (ID=44)Stone Slab
		askingBlock.add(new BlockTypeData(Material.STEP, 1));						// (ID=44)SandStone Slab
		askingBlock.add(new BlockTypeData(Material.STEP, 3));						// (ID=44)CubbleStone Slab
		askingBlock.add(new BlockTypeData(Material.STEP, 4));						// (ID=44)Brick Slab
		askingBlock.add(new BlockTypeData(Material.STEP, 5));						// (ID=44)StoneBrick Slab
		askingBlock.add(new BlockTypeData(Material.STEP, 6));						// (ID=44)Neither Brick Slab
		askingBlock.add(new BlockTypeData(Material.STEP, 7));						// (ID=44)Quartz Slab
		askingBlock.add(new BlockTypeData(Material.BRICK, 0));						// (ID=45)Brick
		askingBlock.add(new BlockTypeData(Material.TNT, 0));						// (ID=46)TNT
		askingBlock.add(new BlockTypeData(Material.BOOKSHELF, 0));					// (ID=47)Bookshelf
		askingBlock.add(new BlockTypeData(Material.MOSSY_COBBLESTONE, 0));			// (ID=48)Mossy CobbleStone
		askingBlock.add(new BlockTypeData(Material.OBSIDIAN, 0));					// (ID=49)Obsidian
		askingBlock.add(new BlockTypeData(Material.TORCH, 0));						// (ID=50)Torch
		askingBlock.add(new BlockTypeData(Material.WOOD_STAIRS, 0));				// (ID=53)Oak Wood Stairs
		askingBlock.add(new BlockTypeData(Material.CHEST, 0));						// (ID=54)Chest
		askingBlock.add(new BlockTypeData(Material.DIAMOND_ORE, 0));				// (ID=56)Diamond Ore
		askingBlock.add(new BlockTypeData(Material.DIAMOND_BLOCK, 0));				// (ID=57)Diamond Block
		askingBlock.add(new BlockTypeData(Material.WORKBENCH, 0));					// (ID=58)Workbench
		askingBlock.add(new BlockTypeData(Material.FURNACE, 0));					// (ID=61)Furnace
		askingBlock.add(new BlockTypeData(Material.SIGN_POST, 0));					// (ID=63)Sign
		askingBlock.add(new BlockTypeData(Material.RAILS, 0));						// (ID=66)Rails
		askingBlock.add(new BlockTypeData(Material.COBBLESTONE_STAIRS, 0));			// (ID=67)CobbleStone Stairs
		//askingBlock.add(new BlockTypeData(Material.LEVER, 0));					// (ID=69)Lever
		askingBlock.add(new BlockTypeData(Material.STONE_PLATE, 0));				// (ID=70)Stone Plate
		askingBlock.add(new BlockTypeData(Material.WOOD_PLATE, 0));					// (ID=72)Wood Plate
		askingBlock.add(new BlockTypeData(Material.REDSTONE_ORE, 0));				// (ID=73)Redstone Ore
		askingBlock.add(new BlockTypeData(Material.REDSTONE_TORCH_ON, 0));			// (ID=76)Redstone Torch
		askingBlock.add(new BlockTypeData(Material.ICE, 0));						// (ID=79)Ice
		askingBlock.add(new BlockTypeData(Material.SNOW_BLOCK, 0));					// (ID=80)Snow Block
		askingBlock.add(new BlockTypeData(Material.CLAY, 0));						// (ID=82)Clay Block
		askingBlock.add(new BlockTypeData(Material.JUKEBOX, 0));					// (ID=84)JukeBox
		askingBlock.add(new BlockTypeData(Material.FENCE, 0));						// (ID=85)Oak Fence
		askingBlock.add(new BlockTypeData(Material.PUMPKIN, 0));					// (ID=86)Pumpkin
		askingBlock.add(new BlockTypeData(Material.NETHERRACK, 0));					// (ID=87)Netherrack
		askingBlock.add(new BlockTypeData(Material.SOUL_SAND, 0));					// (ID=88)Soul Sand
		askingBlock.add(new BlockTypeData(Material.GLOWSTONE, 0));					// (ID=89)GlowStone
		askingBlock.add(new BlockTypeData(Material.JACK_O_LANTERN, 0));				// (ID=91)Jack'o'Lantern
		askingBlock.add(new BlockTypeData(Material.CAKE_BLOCK, 0));					// (ID=92)Cake
		askingBlock.add(new BlockTypeData(Material.STAINED_GLASS, 0));				// (ID=95)White Stained Glass
		askingBlock.add(new BlockTypeData(Material.STAINED_GLASS, 1));				// (ID=95)Orange Stained Glass
		askingBlock.add(new BlockTypeData(Material.STAINED_GLASS, 2));				// (ID=95)Magenta Stained Glass
		askingBlock.add(new BlockTypeData(Material.STAINED_GLASS, 3));				// (ID=95)Light Blue Stained Glass
		askingBlock.add(new BlockTypeData(Material.STAINED_GLASS, 4));				// (ID=95)Yellow Stained Glass
		askingBlock.add(new BlockTypeData(Material.STAINED_GLASS, 5));				// (ID=95)Lime Stained Glass
		askingBlock.add(new BlockTypeData(Material.STAINED_GLASS, 6));				// (ID=95)Pink Stained Glass
		askingBlock.add(new BlockTypeData(Material.STAINED_GLASS, 7));				// (ID=95)Gray Stained Glass
		askingBlock.add(new BlockTypeData(Material.STAINED_GLASS, 8));				// (ID=95)Light Gray Stained Glass
		askingBlock.add(new BlockTypeData(Material.STAINED_GLASS, 9));				// (ID=95)Cyan Stained Glass
		askingBlock.add(new BlockTypeData(Material.STAINED_GLASS, 10));				// (ID=95)Purple Stained Glass
		askingBlock.add(new BlockTypeData(Material.STAINED_GLASS, 11));				// (ID=95)Blue Stained Glass
		askingBlock.add(new BlockTypeData(Material.STAINED_GLASS, 12));				// (ID=95)Brown Stained Glass
		askingBlock.add(new BlockTypeData(Material.STAINED_GLASS, 13));				// (ID=95)Green Stained Glass
		askingBlock.add(new BlockTypeData(Material.STAINED_GLASS, 14));				// (ID=95)Red Stained Glass
		askingBlock.add(new BlockTypeData(Material.STAINED_GLASS, 15));				// (ID=95)Black Stained Glass
		askingBlock.add(new BlockTypeData(Material.TRAP_DOOR, 0));					// (ID=96)Trap Door
		askingBlock.add(new BlockTypeData(Material.SMOOTH_BRICK, 0));				// (ID=98)Stone Brick
		askingBlock.add(new BlockTypeData(Material.SMOOTH_BRICK, 1));				// (ID=98)Mossy Stone Brick
		askingBlock.add(new BlockTypeData(Material.SMOOTH_BRICK, 2));				// (ID=98)Cracked Stone Brick
		askingBlock.add(new BlockTypeData(Material.SMOOTH_BRICK, 3));				// (ID=98)Chiseled Stone Brick
		askingBlock.add(new BlockTypeData(Material.HUGE_MUSHROOM_1, 0));			// (ID=99)Brown Mushroom Block
		askingBlock.add(new BlockTypeData(Material.HUGE_MUSHROOM_2, 0));			// (ID=100)Red Mushroom Block
		askingBlock.add(new BlockTypeData(Material.IRON_FENCE, 0));					// (ID=101)Iron Fence
		askingBlock.add(new BlockTypeData(Material.THIN_GLASS, 0));					// (ID=102)Glass Pane
		askingBlock.add(new BlockTypeData(Material.MELON_BLOCK, 0));				// (ID=103)Melon Block
		askingBlock.add(new BlockTypeData(Material.FENCE_GATE, 0));					// (ID=107)Fence Gate
		askingBlock.add(new BlockTypeData(Material.BRICK_STAIRS, 0));				// (ID=108)Brick Stairs
		askingBlock.add(new BlockTypeData(Material.SMOOTH_STAIRS, 0));				// (ID=109)Stone Brick Stairs
		askingBlock.add(new BlockTypeData(Material.MYCEL, 0));						// (ID=110)Mycelium
		askingBlock.add(new BlockTypeData(Material.NETHER_BRICK, 0));				// (ID=112)Nether Brick
		askingBlock.add(new BlockTypeData(Material.NETHER_FENCE, 0));				// (ID=113)Nether Fence
		askingBlock.add(new BlockTypeData(Material.NETHER_BRICK_STAIRS, 0));		// (ID=114)Nether Brick Stairs
		askingBlock.add(new BlockTypeData(Material.ENCHANTMENT_TABLE, 0));			// (ID=116)Mycelium
		askingBlock.add(new BlockTypeData(Material.BREWING_STAND, 0));				// (ID=117)Brewing Stand
		askingBlock.add(new BlockTypeData(Material.CAULDRON, 0));					// (ID=118)Cauldron
		askingBlock.add(new BlockTypeData(Material.ENDER_STONE, 0));				// (ID=121)Ender Stone
		askingBlock.add(new BlockTypeData(Material.DRAGON_EGG, 0));					// (ID=122)Dragon Egg
		askingBlock.add(new BlockTypeData(Material.REDSTONE_LAMP_OFF, 0));			// (ID=123)Redstone Lamp
		askingBlock.add(new BlockTypeData(Material.WOOD_STEP, 0));					// (ID=123)Oak Wood Slab
		askingBlock.add(new BlockTypeData(Material.WOOD_STEP, 1));					// (ID=123)Spruce Wood Slab
		askingBlock.add(new BlockTypeData(Material.WOOD_STEP, 2));					// (ID=123)Birch Wood Slab
		askingBlock.add(new BlockTypeData(Material.WOOD_STEP, 3));					// (ID=123)Jungle Wood Slab
		askingBlock.add(new BlockTypeData(Material.WOOD_STEP, 4));					// (ID=123)Acacia Wood Slab
		askingBlock.add(new BlockTypeData(Material.WOOD_STEP, 5));					// (ID=123)Dark Wood Slab
		askingBlock.add(new BlockTypeData(Material.SANDSTONE_STAIRS, 0));			// (ID=128)Sand Stone Stairs
		askingBlock.add(new BlockTypeData(Material.EMERALD_ORE, 0));				// (ID=129)Emerald Ore
		askingBlock.add(new BlockTypeData(Material.ENDER_CHEST, 0));				// (ID=130)Ender Chest
		//askingBlock.add(new BlockTypeData(Material.TRIPWIRE_HOOK, 0));			// (ID=131)Tripwire Hook
		askingBlock.add(new BlockTypeData(Material.EMERALD_BLOCK, 0));				// (ID=133)Emerald Block
		askingBlock.add(new BlockTypeData(Material.SPRUCE_WOOD_STAIRS, 0));			// (ID=134)Spruce Wood Stairs
		askingBlock.add(new BlockTypeData(Material.BIRCH_WOOD_STAIRS, 0));			// (ID=135)Birch Wood Stairs
		askingBlock.add(new BlockTypeData(Material.JUNGLE_WOOD_STAIRS, 0));			// (ID=136)Jungle Wood Stairs
		askingBlock.add(new BlockTypeData(Material.BEACON, 0));						// (ID=138)Beacon
		askingBlock.add(new BlockTypeData(Material.COBBLE_WALL, 0));				// (ID=139)Cobble Wall
		askingBlock.add(new BlockTypeData(Material.COBBLE_WALL, 1));				// (ID=139)Mossy Cobble Wall
		askingBlock.add(new BlockTypeData(Material.FLOWER_POT, 0));					// (ID=140)Flower Pot
		askingBlock.add(new BlockTypeData(Material.ANVIL, 0));						// (ID=145)Anvil
		askingBlock.add(new BlockTypeData(Material.ANVIL, 1));						// (ID=145)Slightly Damaged Anvil
		askingBlock.add(new BlockTypeData(Material.ANVIL, 2));						// (ID=145)Very Damaged Anvil
		askingBlock.add(new BlockTypeData(Material.TRAPPED_CHEST, 0));				// (ID=146)Trapped Chest
		askingBlock.add(new BlockTypeData(Material.GOLD_PLATE, 0));					// (ID=147)Gold Plate
		askingBlock.add(new BlockTypeData(Material.IRON_PLATE, 0));					// (ID=148)Iron Plate
		askingBlock.add(new BlockTypeData(Material.REDSTONE_COMPARATOR_OFF, 0));	// (ID=149)Comparator
		askingBlock.add(new BlockTypeData(Material.DAYLIGHT_DETECTOR, 0));			// (ID=151)Daylight Detector
		askingBlock.add(new BlockTypeData(Material.REDSTONE_BLOCK, 0));				// (ID=152)Redstone Block
		askingBlock.add(new BlockTypeData(Material.QUARTZ_ORE, 0));					// (ID=153)Quartz Ore
		askingBlock.add(new BlockTypeData(Material.HOPPER, 0));						// (ID=154)Hopper
		askingBlock.add(new BlockTypeData(Material.QUARTZ_BLOCK, 0));				// (ID=155)Quartz Block
		askingBlock.add(new BlockTypeData(Material.QUARTZ_BLOCK, 1));				// (ID=155)Chiseled Quartz Block
		askingBlock.add(new BlockTypeData(Material.QUARTZ_BLOCK, 2));				// (ID=155)Pillar Quartz Block
		askingBlock.add(new BlockTypeData(Material.QUARTZ_STAIRS, 0));				// (ID=156)Quartz Stairs
		askingBlock.add(new BlockTypeData(Material.ACTIVATOR_RAIL, 0));				// (ID=157)Activator Rail
		askingBlock.add(new BlockTypeData(Material.DROPPER, 0));					// (ID=158)Dropper
		askingBlock.add(new BlockTypeData(Material.STAINED_CLAY, 0));				// (ID=159)White Stained Clay
		askingBlock.add(new BlockTypeData(Material.STAINED_CLAY, 1));				// (ID=159)Orange Stained Clay
		askingBlock.add(new BlockTypeData(Material.STAINED_CLAY, 2));				// (ID=159)Magenta Stained Clay
		askingBlock.add(new BlockTypeData(Material.STAINED_CLAY, 3));				// (ID=159)Light Blue Stained Clay
		askingBlock.add(new BlockTypeData(Material.STAINED_CLAY, 4));				// (ID=159)Yellow Stained Clay
		askingBlock.add(new BlockTypeData(Material.STAINED_CLAY, 5));				// (ID=159)Lime Stained Clay
		askingBlock.add(new BlockTypeData(Material.STAINED_CLAY, 6));				// (ID=159)Pink Stained Clay
		askingBlock.add(new BlockTypeData(Material.STAINED_CLAY, 7));				// (ID=159)Gray Stained Clay
		askingBlock.add(new BlockTypeData(Material.STAINED_CLAY, 8));				// (ID=159)Light Gray Stained Clay
		askingBlock.add(new BlockTypeData(Material.STAINED_CLAY, 9));				// (ID=159)Cyan Stained Clay
		askingBlock.add(new BlockTypeData(Material.STAINED_CLAY, 10));				// (ID=159)Purple Stained Clay
		askingBlock.add(new BlockTypeData(Material.STAINED_CLAY, 11));				// (ID=159)Blue Stained Clay
		askingBlock.add(new BlockTypeData(Material.STAINED_CLAY, 12));				// (ID=159)Brown Stained Clay
		askingBlock.add(new BlockTypeData(Material.STAINED_CLAY, 13));				// (ID=159)Green Stained Clay
		askingBlock.add(new BlockTypeData(Material.STAINED_CLAY, 14));				// (ID=159)Red Stained Clay
		askingBlock.add(new BlockTypeData(Material.STAINED_CLAY, 15));				// (ID=159)Black Stained Clay
		askingBlock.add(new BlockTypeData(Material.STAINED_GLASS_PANE, 0));			// (ID=160)White Stained Glass Pane
		askingBlock.add(new BlockTypeData(Material.STAINED_GLASS_PANE, 1));			// (ID=160)Orange Stained Glass Pane
		askingBlock.add(new BlockTypeData(Material.STAINED_GLASS_PANE, 2));			// (ID=160)Magenta Stained Glass Pane
		askingBlock.add(new BlockTypeData(Material.STAINED_GLASS_PANE, 3));			// (ID=160)Light Blue Stained Glass Pane
		askingBlock.add(new BlockTypeData(Material.STAINED_GLASS_PANE, 4));			// (ID=160)Yellow Stained Glass Pane
		askingBlock.add(new BlockTypeData(Material.STAINED_GLASS_PANE, 5));			// (ID=160)Lime Stained Glass Pane
		askingBlock.add(new BlockTypeData(Material.STAINED_GLASS_PANE, 6));			// (ID=160)Pink Stained Glass Pane
		askingBlock.add(new BlockTypeData(Material.STAINED_GLASS_PANE, 7));			// (ID=160)Gray Stained Glass Pane
		askingBlock.add(new BlockTypeData(Material.STAINED_GLASS_PANE, 8));			// (ID=160)Light Gray Stained Glass Pane
		askingBlock.add(new BlockTypeData(Material.STAINED_GLASS_PANE, 9));			// (ID=160)Cyan Stained Glass Pane
		askingBlock.add(new BlockTypeData(Material.STAINED_GLASS_PANE, 10));		// (ID=160)Purple Stained Glass Pane
		askingBlock.add(new BlockTypeData(Material.STAINED_GLASS_PANE, 11));		// (ID=160)Blue Stained Glass Pane
		askingBlock.add(new BlockTypeData(Material.STAINED_GLASS_PANE, 12));		// (ID=160)Brown Stained Glass Pane
		askingBlock.add(new BlockTypeData(Material.STAINED_GLASS_PANE, 13));		// (ID=160)Green Stained Glass Pane
		askingBlock.add(new BlockTypeData(Material.STAINED_GLASS_PANE, 14));		// (ID=160)Red Stained Glass Pane
		askingBlock.add(new BlockTypeData(Material.STAINED_GLASS_PANE, 15));		// (ID=160)Black Stained Glass Pane
		askingBlock.add(new BlockTypeData(Material.LEAVES_2, 0));					// (ID=161)Acacia Leaves
		askingBlock.add(new BlockTypeData(Material.LEAVES_2, 1));					// (ID=161)Dark Oak Leaves
		askingBlock.add(new BlockTypeData(Material.LOG_2, 0));						// (ID=162)Acacia Wood
		askingBlock.add(new BlockTypeData(Material.LOG_2, 1));						// (ID=162)Dark Oak Wood
		askingBlock.add(new BlockTypeData(Material.ACACIA_STAIRS, 0));				// (ID=163)Acacia Stairs
		askingBlock.add(new BlockTypeData(Material.DARK_OAK_STAIRS, 0));			// (ID=164)Dark Oak Stairs
		askingBlock.add(new BlockTypeData(Material.SLIME_BLOCK, 0));				// (ID=165)Slime Block
		askingBlock.add(new BlockTypeData(Material.IRON_TRAPDOOR, 0));				// (ID=167)Iron Trapdoor
		askingBlock.add(new BlockTypeData(Material.PRISMARINE, 0));					// (ID=168)Prismarine
		askingBlock.add(new BlockTypeData(Material.SEA_LANTERN, 0));				// (ID=169)Sea Lantern
		askingBlock.add(new BlockTypeData(Material.HAY_BLOCK, 0));					// (ID=170)Hay Bale
		askingBlock.add(new BlockTypeData(Material.CARPET, 0));						// (ID=171)White Carpet
		askingBlock.add(new BlockTypeData(Material.CARPET, 1));						// (ID=171)Orange Carpet
		askingBlock.add(new BlockTypeData(Material.CARPET, 2));						// (ID=171)Magenta Carpet
		askingBlock.add(new BlockTypeData(Material.CARPET, 3));						// (ID=171)Light Blue Carpet
		askingBlock.add(new BlockTypeData(Material.CARPET, 4));						// (ID=171)Yellow Carpet
		askingBlock.add(new BlockTypeData(Material.CARPET, 5));						// (ID=171)Lime Carpet
		askingBlock.add(new BlockTypeData(Material.CARPET, 6));						// (ID=171)Pink Carpet
		askingBlock.add(new BlockTypeData(Material.CARPET, 7));						// (ID=171)Gray Carpet
		askingBlock.add(new BlockTypeData(Material.CARPET, 8));						// (ID=171)Light Gray Carpet
		askingBlock.add(new BlockTypeData(Material.CARPET, 9));						// (ID=171)Cyan Carpet
		askingBlock.add(new BlockTypeData(Material.CARPET, 10));					// (ID=171)Purple Carpet
		askingBlock.add(new BlockTypeData(Material.CARPET, 11));					// (ID=171)Blue Carpet
		askingBlock.add(new BlockTypeData(Material.CARPET, 12));					// (ID=171)Brown Carpet
		askingBlock.add(new BlockTypeData(Material.CARPET, 13));					// (ID=171)Green Carpet
		askingBlock.add(new BlockTypeData(Material.CARPET, 14));					// (ID=171)Red Carpet
		askingBlock.add(new BlockTypeData(Material.CARPET, 15));					// (ID=171)Black Carpet
		askingBlock.add(new BlockTypeData(Material.HARD_CLAY, 0));					// (ID=172)Hard Clay
		askingBlock.add(new BlockTypeData(Material.COAL_BLOCK, 0));					// (ID=173)Coal Block
		askingBlock.add(new BlockTypeData(Material.PACKED_ICE, 0));					// (ID=174)Packed Ice
		askingBlock.add(new BlockTypeData(Material.RED_SANDSTONE, 0));				// (ID=179)Red Sandstone
		askingBlock.add(new BlockTypeData(Material.RED_SANDSTONE, 1));				// (ID=179)Chiseled Red Sandstone
		askingBlock.add(new BlockTypeData(Material.RED_SANDSTONE, 2));				// (ID=179)Smooth Red Sandstone
		askingBlock.add(new BlockTypeData(Material.RED_SANDSTONE_STAIRS, 0));		// (ID=180)Red Sandstone Stairs
		askingBlock.add(new BlockTypeData(Material.STONE_SLAB2, 0));				// (ID=182)Red Sandstone Slab
		askingBlock.add(new BlockTypeData(Material.SPRUCE_FENCE_GATE, 0));			// (ID=183)Spruce Fence Gate
		askingBlock.add(new BlockTypeData(Material.BIRCH_FENCE_GATE, 0));			// (ID=184)Birch Fence Gate
		askingBlock.add(new BlockTypeData(Material.JUNGLE_FENCE_GATE, 0));			// (ID=185)Jungle Fence Gate
		askingBlock.add(new BlockTypeData(Material.DARK_OAK_FENCE_GATE, 0));		// (ID=186)Dark Oak Fence Gate
		askingBlock.add(new BlockTypeData(Material.ACACIA_FENCE_GATE, 0));			// (ID=187)Acacia Fence Gate
		askingBlock.add(new BlockTypeData(Material.SPRUCE_FENCE, 0));				// (ID=188)Spruce Fence
		askingBlock.add(new BlockTypeData(Material.BIRCH_FENCE, 0));				// (ID=189)Birch Fence
		askingBlock.add(new BlockTypeData(Material.JUNGLE_FENCE, 0));				// (ID=190)Jungle Fence
		askingBlock.add(new BlockTypeData(Material.DARK_OAK_FENCE, 0));				// (ID=191)Dark Oak Fence
		askingBlock.add(new BlockTypeData(Material.ACACIA_FENCE, 0));				// (ID=192)Acacia Fence
		askingBlock.add(new BlockTypeData(Material.END_ROD, 0));					// (ID=198)End Rod
		askingBlock.add(new BlockTypeData(Material.PURPUR_BLOCK, 0));				// (ID=201)Purpur Block
		askingBlock.add(new BlockTypeData(Material.PURPUR_PILLAR, 0));				// (ID=202)Purpur Pillar
		askingBlock.add(new BlockTypeData(Material.PURPUR_STAIRS, 0));				// (ID=203)Purpur Stairs
		askingBlock.add(new BlockTypeData(Material.PURPUR_SLAB, 0));				// (ID=205)Purpur Slab
		askingBlock.add(new BlockTypeData(Material.END_BRICKS, 0));					// (ID=206)End Brick
		askingBlock.add(new BlockTypeData(Material.MAGMA, 0));						// (ID=202)Magma Block
		askingBlock.add(new BlockTypeData(Material.NETHER_WART_BLOCK, 0));			// (ID=203)Nether Wart Block
		askingBlock.add(new BlockTypeData(Material.RED_NETHER_BRICK, 0));			// (ID=205)Red Nether Brick
		askingBlock.add(new BlockTypeData(Material.BONE_BLOCK, 0));					// (ID=206)Bone Block
		//@formatter:on
	}

	public List<BlockTypeData> getAskingBlock() {
		return askingBlock;
	}

	public void setAskingBlock(List<BlockTypeData> askingBlock) {
		this.askingBlock = askingBlock;
	}
}
